name: nodelabs_case
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  firebase_analytics: ^12.0.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  go_router: ^16.0.0
  hive_ce: ^2.11.3
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  kartal: ^4.2.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  vexana: ^5.0.3
  flutter_svg: ^2.2.0
  envied: ^1.2.0

flutter_gen:
  output: lib/product/generated/
  integrations:
    lottie: true
    flutter_svg: true

flutter_launcher_icons:
  android: true
  image_path_android: "assets/png/sin_flix_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/png/sin_flix_logo.png"
  min_sdk_android: 21
  ios: true
  image_path_ios: "assets/png/sin_flix_logo.png"
  remove_alpha_channel_ios: true
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  hive_ce_generator: ^1.9.3
  flutter_gen_runner: ^5.11.0
  json_serializable: ^6.10.0
  envied_generator: ^1.2.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/font/
    - assets/env/
    - assets/png/

  fonts:
    - family: EuclidCircularA
      fonts:
        - asset: assets/font/euclid_circular_a/euclid_circular_a_light.ttf
          weight: 300
        - asset: assets/font/euclid_circular_a/euclid_circular_a_light_italic.ttf
          weight: 300
          style: italic
        - asset: assets/font/euclid_circular_a/euclid_circular_a_regular.ttf
          weight: 400
        - asset: assets/font/euclid_circular_a/euclid_circular_a_italic.ttf
          weight: 400
          style: italic
        - asset: assets/font/euclid_circular_a/euclid_circular_a_medium.ttf
          weight: 500
        - asset: assets/font/euclid_circular_a/euclid_circular_a_medium_italic.ttf
          weight: 500
          style: italic
        - asset: assets/font/euclid_circular_a/euclid_circular_a_semibold.ttf
          weight: 600
        - asset: assets/font/euclid_circular_a/euclid_circular_a_semibold_italic.ttf
          weight: 600
          style: italic
        - asset: assets/font/euclid_circular_a/euclid_circular_a_bold.ttf
          weight: 700
        - asset: assets/font/euclid_circular_a/euclid_circular_a_bold_italic.ttf
          weight: 700
          style: italic
    - family: Montserrat
      fonts:
        - asset: assets/font/montserrat/montserrat_semibold.ttf
          weight: 600
        - asset: assets/font/montserrat/montserrat_black.ttf
          weight: 900
